#!/bin/bash 

scp dumbo:/storage2/common/restarts/80/*.80 output
scp dumbo:/storage2/common/restarts/40/*.40 output

cp scons_repo/SConstruct_Run SConstruct
scons-3
cp namelistSIM_control namelistSIM
